### PR TITLE
Fix adb40

### PR DESCRIPTION
**Pull request by codeskyblue**

### CODE REVIEW

**Comment by codeskyblue** [comment]
Ref: https://github.com/openstf/stf/issues/973

**Comment by esmiralha** [comment]
Is this PR merged yet?

**Comment by thinkhy** [comment]
I've tested this PR for adb 1.0.40 latest version, it works well.
@sorccu the bug will cause STF provider crash when use adb latest version to connect adbkit tcp bridge, we need to merge this PR ...

**Comment by codeskyblue** [comment]
I use `npm i --save codeskyblue/adbkit#fix-adb40` instead of `npm i --save adbkit` for hotfix.

**Comment by codeskyblue** [comment]
I publish another lib to npm named `adbkit2`, installed by `npm i adbkit2` for hotfix.

**Comment by sorccu** [comment]
Guys, you need to be more patient. Even if it’s a relatively large issue, paid work takes priority. I’ll try to get this merged and released sometime soon.

**Comment by codeskyblue** [comment]
@sorccu when will you be free?

**Pull request merged**
